/* MISEVO — Categorias de Produção */
const PADRAO=[["Bases e Fundos",1],["Molhos",2],["Carnes e Aves",3],["Pescados e Frutos do Mar",4],["Massas",5],["Arroz e Cereais",6],["Guarnições",7],["Vegetais e Saladas",8],["Padaria",9],["Confeitaria e Sobremesas",10],["Marinadas e Condimentos",11],["Pré-preparos",12]];
export async function initCategorias(pool){
 await pool.query(`CREATE TABLE IF NOT EXISTS categorias_producao(id BIGSERIAL PRIMARY KEY,nome TEXT NOT NULL,descricao TEXT NOT NULL DEFAULT '',ativo BOOLEAN NOT NULL DEFAULT TRUE,ordem INTEGER NOT NULL DEFAULT 0,empresa_id BIGINT NOT NULL,unidade_id BIGINT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(empresa_id,unidade_id,nome));CREATE INDEX IF NOT EXISTS idx_categorias_tenant ON categorias_producao(empresa_id,unidade_id,ordem,nome);`);
 const {rows}=await pool.query(`SELECT DISTINCT empresa_id,unidade_id FROM usuarios WHERE empresa_id IS NOT NULL AND unidade_id IS NOT NULL`);
 for(const t of rows)for(const [nome,ordem] of PADRAO)await pool.query(`INSERT INTO categorias_producao(nome,ordem,empresa_id,unidade_id) VALUES($1,$2,$3,$4) ON CONFLICT(empresa_id,unidade_id,nome) DO NOTHING`,[nome,ordem,t.empresa_id,t.unidade_id]);
}
export function installCategorias(app,pool){
 app.get("/api/categorias",async(req,res,next)=>{try{res.set("Cache-Control","no-store, no-cache, must-revalidate, proxy-revalidate");res.set("Pragma","no-cache");res.set("Expires","0");const {rows}=await pool.query(`SELECT c.*,(SELECT COUNT(*)::integer FROM fichas f WHERE f.empresa_id=c.empresa_id AND f.unidade_id=c.unidade_id AND f.categoria=c.nome) fichas,(SELECT COUNT(*)::integer FROM preparacoes p WHERE p.empresa_id=c.empresa_id AND p.unidade_id=c.unidade_id AND p.categoria=c.nome) preparacoes FROM categorias_producao c WHERE c.empresa_id=$1 AND c.unidade_id=$2 ORDER BY c.ordem,c.nome`,[req.user.empresa_id,req.user.unidade_id]);res.json(rows)}catch(e){next(e)}});
 app.post("/api/categorias",async(req,res,next)=>{try{const nome=String(req.body.nome||"").trim();if(!nome)return res.status(400).json({error:"Informe o nome da categoria."});const {rows}=await pool.query(`INSERT INTO categorias_producao(nome,descricao,ativo,ordem,empresa_id,unidade_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[nome,String(req.body.descricao||"").trim(),req.body.ativo!==false,Number(req.body.ordem)||999,req.user.empresa_id,req.user.unidade_id]);res.status(201).json(rows[0])}catch(e){if(e.code==="23505")return res.status(409).json({error:"Já existe uma categoria com esse nome."});next(e)}});
 app.put("/api/categorias/:id",async(req,res,next)=>{const c=await pool.connect();try{await c.query("BEGIN");const old=await c.query(`SELECT * FROM categorias_producao WHERE id=$1 AND empresa_id=$2 AND unidade_id=$3`,[req.params.id,req.user.empresa_id,req.user.unidade_id]);if(!old.rows[0]){await c.query("ROLLBACK");return res.status(404).json({error:"Categoria não encontrada."})}const nome=String(req.body.nome||"").trim();if(!nome){await c.query("ROLLBACK");return res.status(400).json({error:"Informe o nome da categoria."})}if(nome!==old.rows[0].nome){await c.query(`UPDATE fichas SET categoria=$1,updated_at=NOW() WHERE empresa_id=$2 AND unidade_id=$3 AND categoria=$4`,[nome,req.user.empresa_id,req.user.unidade_id,old.rows[0].nome]);await c.query(`UPDATE preparacoes SET categoria=$1,updated_at=NOW() WHERE empresa_id=$2 AND unidade_id=$3 AND categoria=$4`,[nome,req.user.empresa_id,req.user.unidade_id,old.rows[0].nome])}const {rows}=await c.query(`UPDATE categorias_producao SET nome=$1,descricao=$2,ativo=$3,ordem=$4,updated_at=NOW() WHERE id=$5 AND empresa_id=$6 AND unidade_id=$7 RETURNING *`,[nome,String(req.body.descricao||"").trim(),req.body.ativo!==false,Number(req.body.ordem)||old.rows[0].ordem,req.params.id,req.user.empresa_id,req.user.unidade_id]);await c.query("COMMIT");res.json(rows[0])}catch(e){await c.query("ROLLBACK");if(e.code==="23505")return res.status(409).json({error:"Já existe uma categoria com esse nome."});next(e)}finally{c.release()}});
 app.delete("/api/categorias/:id",async(req,res,next)=>{try{const c=await pool.query(`SELECT * FROM categorias_producao WHERE id=$1 AND empresa_id=$2 AND unidade_id=$3`,[req.params.id,req.user.empresa_id,req.user.unidade_id]);if(!c.rows[0])return res.status(404).json({error:"Categoria não encontrada."});const u=await pool.query(`SELECT (SELECT COUNT(*) FROM fichas WHERE empresa_id=$1 AND unidade_id=$2 AND categoria=$3)+(SELECT COUNT(*) FROM preparacoes WHERE empresa_id=$1 AND unidade_id=$2 AND categoria=$3) total`,[req.user.empresa_id,req.user.unidade_id,c.rows[0].nome]);if(Number(u.rows[0].total)>0)return res.status(409).json({error:"Esta categoria está em uso. Desative-a em vez de excluir."});await pool.query(`DELETE FROM categorias_producao WHERE id=$1 AND empresa_id=$2 AND unidade_id=$3`,[req.params.id,req.user.empresa_id,req.user.unidade_id]);res.status(204).end()}catch(e){next(e)}});
}